### ISSUE TITLE
Dry run flag

### ISSUE THREAD

**Issue by lauriejones** [jameslnewell/publish-if-not-published#1]
Possibly a nice addition for people setting this up for the first time.

```sh
publish-if-not-published --dry-run
```

A flag that replaces the actual `npm publish` command with some logging or just nothing?

**Comment by jameslnewell** [comment]
Should be pretty easy just adding an [extra condition](https://github.com/jameslnewell/publish-if-not-published/blob/master/src/index.ts#L36)?

Want to have a crack at it?

**Comment by lauriejones** [comment]
Sure! 👍

**Comment by jameslnewell** [comment]
`npm` already has a `--dry-run` flag which can be be passed though it doesn't error if the package version already exists.

https://docs.npmjs.com/cli/publish
